
# services:
#     app.pipeline_event_processor:
#         class: AppBundle\Service\PipelineEventProcessor
#         calls:
#             - ['setContainer', ['@service_container']]
#         tags:
#             - { name: kernel.event_listener, event: tracker.updated }
#         